# Generated by Django 2.2.6 on 2019-10-24 02:02

from django.utils.datetime_safe import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.IntegerField()),
                ('telefone', models.CharField(max_length=15)),
                ('saldo_bancario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dt_cadastro', models.DateTimeField(default=datetime(2019, 10, 24, 2, 2, 44, 254340))),
            ],
        ),
    ]
